import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createApp } from '../server/index.mjs';
import { buildRequest, normalizeResponse } from '../server/decisions.mjs';
const origin='http://localhost:3000';
const key='test-key-not-real';
const context={ticket:{message:'refund duplicate charge'}};
const response=()=>new Response(JSON.stringify({model:'jev-test',answers:{decision:{type:'choice',choice:'billing',confidence:.92,probabilities:{billing:.92,technical:.05,other:.03}}}}),{headers:{'Content-Type':'application/json'}});
async function setup(t, options={}){const server=createApp({fetchImpl:async()=>response(),...options});server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>new Promise(r=>{server.close(r);server.closeAllConnections()}));const url=`http://127.0.0.1:${server.address().port}`;return {url,post:(body={scenario:'support',context},headers={})=>fetch(url+'/api/decision',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Jev-Key':key,...headers},body:JSON.stringify(body)})};}
test('live request uses fixed endpoint, key header, real schema, and no key in response',async t=>{let calls=0;const {post}=await setup(t,{fetchImpl:async(url,init)=>{calls++;assert.equal(url,'https://api.typesafe.ai/v1/systemone');assert.equal(init.headers.Authorization,`Bearer ${key}`);assert.equal(init.redirect,'error');const b=JSON.parse(init.body);assert.equal(b.questions.decision.type,'choice');assert.deepEqual(b.state,context);assert.equal(b.apiKey,undefined);return response()}});const res=await post();assert.equal(res.status,200);assert.equal(res.headers.get('cache-control'),'no-store');const body=await res.json();assert.equal(body.mode,'live');assert.equal(body.decision,'billing');assert.equal(calls,1);assert.ok(!JSON.stringify(body).includes(key));});
test('reject foreign origin before provider',async t=>{const {post}=await setup(t,{fetchImpl:()=>assert.fail('provider called')});assert.equal((await post(undefined,{Origin:'https://evil.example'})).status,403)});
test('missing key and wrong content type',async t=>{const {post}=await setup(t);assert.equal((await post(undefined,{'X-Jev-Key':''})).status,401);assert.equal((await post(undefined,{'Content-Type':'text/plain'})).status,415)});
test('invalid contexts, scenarios, and approval flags',async t=>{const {post}=await setup(t,{fetchImpl:()=>assert.fail('provider called')});for(const body of [{scenario:'support',context:{}},{scenario:'unknown',context:{}},{scenario:'guardrails',context:{action:'read',requires_approval:'false'}}])assert.equal((await post(body)).status,400)});
test('invalid JSON rejected',async t=>{const {url}=await setup(t);const res=await fetch(url+'/api/decision',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json','X-Jev-Key':key},body:'{'});assert.equal(res.status,400)});
test('oversized context rejected',async t=>{const {post}=await setup(t);assert.equal((await post({scenario:'support',context:{ticket:{message:'x'.repeat(33000)}}})).status,413)});
for(const status of [401,403,429,500])test(`provider ${status} returns safe error`,async t=>{const {post}=await setup(t,{fetchImpl:async()=>new Response('private secret '+key,{status})});const res=await post();assert.equal(res.status,status===403?401:status===500?502:status);assert.ok(!(await res.text()).includes(key))});
test('provider response validation fails closed',async t=>{const {post}=await setup(t,{fetchImpl:async()=>new Response('{"answers":{"decision":{"type":"choice","choice":"execute-shell","confidence":1}}}')});assert.equal((await post()).status,502)});
test('provider response body size limited',async t=>{const {post}=await setup(t,{fetchImpl:async()=>new Response('x'.repeat(70000))});assert.equal((await post()).status,502)});
test('timeouts abort provider',async t=>{const {post}=await setup(t,{timeoutMs:10,fetchImpl:async(_url,init)=>new Promise((_r,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('secret diagnostic'))))});assert.equal((await post()).status,504)});
test('rate limit enforced',async t=>{const {post}=await setup(t,{rateLimit:1});assert.equal((await post()).status,200);assert.equal((await post()).status,429)});
test('concurrency capped',async t=>{let release,entered;const waiting=new Promise(r=>entered=r);const {post}=await setup(t,{maxConcurrent:1,fetchImpl:()=>new Promise(r=>{release=()=>r(response());entered()})});const first=post();await waiting;assert.equal((await post()).status,429);release();assert.equal((await first).status,200)});
test('static serving uses allowlist and CSP without third party fonts',async t=>{const {url}=await setup(t);const res=await fetch(url);assert.equal(res.status,200);assert.ok(res.headers.get('content-security-policy').includes("connect-src 'self'"));assert.equal((await fetch(url+'/server/index.mjs')).status,404);assert.equal((await fetch(url+'/.env')).status,404);assert.equal((await fetch(url+'/api/decision')).status,405)});
test('yes-no uses probability of yes and carries hard approval flag',()=>{const req=buildRequest({scenario:'guardrails',context:{action:'Read docs',requires_approval:true}});const r=normalizeResponse({answers:{decision:{type:'noul',noul:.9}}},req,'guardrails');assert.equal(r.decision,'yes');assert.equal(r.confidence,.9);assert.equal(r.requiresApproval,true)});
test('score keeps rubric scale separate from confidence',()=>{const req=buildRequest({scenario:'rag',context:{query:'q',document:'d'}});const r=normalizeResponse({answers:{decision:{type:'score',score:1.6,confidence:.72,probabilities:{0:.1,1:.2,2:.7}}}},req,'rag');assert.equal(r.score,1.6);assert.equal(r.maxScore,2);assert.equal(r.confidence,.72)});
test('invalid probability distributions rejected',()=>{const req=buildRequest({scenario:'support',context});assert.throws(()=>normalizeResponse({answers:{decision:{type:'choice',choice:'billing',confidence:.9,probabilities:{billing:.9,technical:.9,other:.9}}}},req,'support'))});
test('public origin requires HTTPS outside loopback',()=>{assert.throws(()=>createApp({publicOrigin:'http://example.com'}));assert.throws(()=>createApp({publicOrigin:'https://example.com/path'}))});
test('API status exposes readiness without provider calls or keys',async t=>{const {url}=await setup(t,{fetchImpl:()=>assert.fail('provider called')});const res=await fetch(url+'/api/status');assert.equal(res.status,200);assert.deepEqual(await res.json(),{ready:true,provider:'typesafe',keyStorage:'none'})});
test('loopback alias works only on configured port',async t=>{const {post}=await setup(t);assert.equal((await post(undefined,{Origin:'http://127.0.0.1:3000'})).status,200);assert.equal((await post(undefined,{Origin:'http://127.0.0.1:4000'})).status,403)});
test('recipe module is served for frontend import',async t=>{const {url}=await setup(t);const res=await fetch(url+'/recipes.js');assert.equal(res.status,200);assert.ok(res.headers.get('content-type').startsWith('text/javascript'))});
for(const scenario of ['router','browser','npc'])test(`${scenario} forwards to real transport and returns provider decision`,async t=>{
 const {recipes}=await import('../dist/recipes.js');
 const {post}=await setup(t,{fetchImpl:async(_url,init)=>{
  const criteria=JSON.parse(init.body).questions.decision.criteria;
  const labels=Object.keys(criteria);const decision=labels.at(-1);
  return new Response(JSON.stringify({model:'jev-test',answers:{decision:{type:'choice',choice:decision,confidence:.88,probabilities:Object.fromEntries(labels.map(k=>[k,k===decision?.88:.12/(labels.length-1)]))}}}));
 }});
 const res=await post({scenario,context:recipes[scenario].input});assert.equal(res.status,200);const data=await res.json();assert.equal(data.mode,'live');assert.equal(data.scenario,scenario);
});
